(define-key global-map [f11] 'nikki93/switch-fullscreen)
(define-key global-map (kbd "C-s") 'save-buffer)
(define-key global-map (kbd "M-s") 'save-buffer)
(define-key evil-normal-state-map ",r" 'nikki93/cgame-scratch)
(define-key evil-visual-state-map ",r" 'nikki93/cgame-scratch)
(define-key evil-normal-state-map ";r" 'nikki93/cgame-scratch)
(define-key evil-visual-state-map ";r" 'nikki93/cgame-scratch)
